"""Add viral_kicks, keyframe_evidences, comment_evidences tables (P1-1)

Revision ID: 6e90df2c244e
Revises: 91e0f4e6baae
Create Date: 2026-01-01 13:47:55.031296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e90df2c244e'
down_revision: Union[str, Sequence[str], None] = '91e0f4e6baae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_evidences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.String(length=100), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('text_snippet', sa.String(length=500), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('matched_kick_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['remix_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_evidences_evidence_id'), 'comment_evidences', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_comment_evidences_node_id'), 'comment_evidences', ['node_id'], unique=False)
    op.create_table('viral_kicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kick_id', sa.String(length=100), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('outlier_item_id', sa.UUID(), nullable=True),
    sa.Column('kick_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('mechanism', sa.String(length=240), nullable=False),
    sa.Column('creator_instruction', sa.String(length=300), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('peak_ms', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('missing_reason', sa.String(length=50), nullable=True),
    sa.Column('proof_ready', sa.Boolean(), nullable=False),
    sa.Column('comment_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('frame_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_comment_ranks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_REVIEW', name='viralkickstatus'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['remix_nodes.id'], ),
    sa.ForeignKeyConstraint(['outlier_item_id'], ['outlier_items.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viral_kicks_confidence'), 'viral_kicks', ['confidence'], unique=False)
    op.create_index(op.f('ix_viral_kicks_kick_id'), 'viral_kicks', ['kick_id'], unique=True)
    op.create_index(op.f('ix_viral_kicks_mechanism'), 'viral_kicks', ['mechanism'], unique=False)
    op.create_index(op.f('ix_viral_kicks_node_id'), 'viral_kicks', ['node_id'], unique=False)
    op.create_index(op.f('ix_viral_kicks_outlier_item_id'), 'viral_kicks', ['outlier_item_id'], unique=False)
    op.create_index(op.f('ix_viral_kicks_proof_ready'), 'viral_kicks', ['proof_ready'], unique=False)
    op.create_table('keyframe_evidences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.String(length=100), nullable=False),
    sa.Column('kick_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('t_ms', sa.Integer(), nullable=False),
    sa.Column('what_to_see', sa.String(length=200), nullable=True),
    sa.Column('blur_score', sa.Float(), nullable=True),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('motion_proxy', sa.Float(), nullable=True),
    sa.Column('frame_hash', sa.String(length=16), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kick_id'], ['viral_kicks.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['remix_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyframe_evidences_evidence_id'), 'keyframe_evidences', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_keyframe_evidences_kick_id'), 'keyframe_evidences', ['kick_id'], unique=False)
    op.create_index(op.f('ix_keyframe_evidences_node_id'), 'keyframe_evidences', ['node_id'], unique=False)
    op.alter_column('outlier_items', 'campaign_eligible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('outlier_items_video_url_key'), 'outlier_items', type_='unique')
    op.drop_index(op.f('ix_outlier_items_video_url'), table_name='outlier_items')
    op.create_index(op.f('ix_outlier_items_video_url'), 'outlier_items', ['video_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outlier_items_video_url'), table_name='outlier_items')
    op.create_index(op.f('ix_outlier_items_video_url'), 'outlier_items', ['video_url'], unique=False)
    op.create_unique_constraint(op.f('outlier_items_video_url_key'), 'outlier_items', ['video_url'], postgresql_nulls_not_distinct=False)
    op.alter_column('outlier_items', 'campaign_eligible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_keyframe_evidences_node_id'), table_name='keyframe_evidences')
    op.drop_index(op.f('ix_keyframe_evidences_kick_id'), table_name='keyframe_evidences')
    op.drop_index(op.f('ix_keyframe_evidences_evidence_id'), table_name='keyframe_evidences')
    op.drop_table('keyframe_evidences')
    op.drop_index(op.f('ix_viral_kicks_proof_ready'), table_name='viral_kicks')
    op.drop_index(op.f('ix_viral_kicks_outlier_item_id'), table_name='viral_kicks')
    op.drop_index(op.f('ix_viral_kicks_node_id'), table_name='viral_kicks')
    op.drop_index(op.f('ix_viral_kicks_mechanism'), table_name='viral_kicks')
    op.drop_index(op.f('ix_viral_kicks_kick_id'), table_name='viral_kicks')
    op.drop_index(op.f('ix_viral_kicks_confidence'), table_name='viral_kicks')
    op.drop_table('viral_kicks')
    op.drop_index(op.f('ix_comment_evidences_node_id'), table_name='comment_evidences')
    op.drop_index(op.f('ix_comment_evidences_evidence_id'), table_name='comment_evidences')
    op.drop_table('comment_evidences')
    # ### end Alembic commands ###
